config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "students#index"

  
   
  

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



    #Command if no image is uploaded for profile picture
    after_commit :add_default_profile_picture, on: %i[create update]

    
    #Presence = true allows for condiontion to be filied
    validates :first_name, presence:true
    validates :last_name, presence:true
    validates :graduation_date, presence:true
   

    #Sprint #2 VALID_MAJORS
    #Purpose is only accept major listed below
    VALID_MAJORS = ["Computer Engineering BS", "Computer Information Systems BS", 
    "Computer Science BS", "Cybersecurity Major", "Data Science and Machine Learning Major"]
    
    #For Before and After
    VALID_BEFOREANDAFTER = ["Before", "After"]
    
    #Major includes validations for text in VALID_MAJORS
    validates :major, inclusion: {in: VALID_MAJORS, message: "%{value} is not a valid major"}

    
    #Uniqueness: true allows for condiontion to be realized
        #Commented out to remove school_email for email
    #validates :school_email, presence: true 
    #validates :school_email, uniqueness:true
    
    #Documentation at active record validations on guides/rubyonrails.org
    #Format is used to make sure school_email has '@msudenver.edu'
        #Commented out to replace with school_email with email
    #validates :school_email, format: { with: /\A[a-zA-Z0-9]+@msudenver.edu\z/,
    #message: "must be a vaild MSU email" }

    #Active Storage Attachment Associations
    has_one_attached :image

    #Validate email_format for Devise
    validate :email_format
    def email_format
       unless email =~ /\A[\w+\-.]+@msudenver\.edu\z/i
           errors.add(:email, "must be an @msudenver.edu email address")
       end
    end



    #Default Profile Picture set if not uploaded
    private
    def add_default_profile_picture
        unless image.attached?
            image.attach(
                io: File.open(
                    Rails.root.join(
                        'app', 'assets', 'images', 'Default_Profile_picture.jpg'
                    )
                ), 
                filename: 'Default_Profile_picture.jpg',
                content_type: 'image/jpg'
            )
        end
    end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @search_params = params[:search] || {}
    
    #Intialize Students to be empty before search
    @students = Student.none

    #If search is present, hide all
    if params[:search].present?
      
      #When search is made, show student index according to filter
      @students = Student.all


      #Major Search, tied to _search_form.html
      if @search_params[:major].present?
        @students = @students.where(major: @search_params[:major])
      end

      #Graduation Date Search on Controller for before/after gradution date
      if @search_params[:graduation_date].present?
        if @search_params[:VALID_BEFOREANDAFTER] == 'Before'
          @students = @students.where('graduation_date <= ?', @search_params[:graduation_date])
        elsif @search_params[:VALID_BEFOREANDAFTER] == 'After'
          @students = @students.where('graduation_date >= ?', @search_params[:graduation_date])
        end

        #Testing for before/after commands parsing graduation date
        #date = Date.parse(@search_params[graduation_date])
        #@students = @students.where('graduation_date <= ?', ...date)
      end
    

    end #End of hide all

    # In the case that there is no search, send this message
    #For testing purposes in Rspec Test #3
    if @students.empty?
      @students_message = "Please enter search criteria to find students" 
    end
  
   

  end

    

  

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :image, :major, :minor, :graduation_date)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  

  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.select :major, options_for_select(Student::VALID_MAJORS), {prompt: "Select a Major"},
    class: "form-control" %>
  </div>

  <div>
    <%= form.label :minor, style: "display: block" %>
    <%= form.text_field :minor %>
  </div>

  <div>
    <%= form.label :graduation_date, style: "display: block" %>
    <%= form.date_field :graduation_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_search_form.html.erb
<%= form_with(url:students_path, method: :get, local: true, class: "form-inline") do |form| %>
    <div>
        <%= form.label :major, "Select Major", class: "form-label" %>
        <%= form.select :major, options_for_select(Student::VALID_MAJORS), {prompt: "Any Major"}, name: 'search[major]',
    class: "form-control" %>
    </div>

    <!--- Documentation for using graduation date comes from 
    #https://guides.rubyonrails.org/form_helpers.html#using-date-and-time-form-helpers -->
    <div>
        <%= form.label :graduation_date, "Select Graduation date" %>
        <%= form.date_field :graduation_date, name: 'search[graduation_date]',
    class: "form-control" %>
    </div>

    <div>
        <%= form.label :before_after, "Choose Before or After" %>
        <%= form.select :before_after, options_for_select(Student::VALID_BEFOREANDAFTER), name: 'search[before_after]',
    class: "form-control" %>
    </div>


    <div>
        <%= form.submit "Search", class: "btn bth-primary" %>
    </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>


  <p>
  <strong>Profile Picture:</strong>
  <br/>
  <% if student.image.present? %>
    <%= image_tag student.image %>
  <% else %>
    <%= image_tag src="https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg" %>
  <% end %>

  </p>

  

  <p>
    <strong>Major:</strong>
    <%= student.major %>
  </p>

  <p>
    <strong>Minor:</strong>
    <%= student.minor %>
  </p>

  <p>
    <strong>Graduation date:</strong>
    <%= student.graduation_date %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<!--<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div> -->

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Major</th>
      <th scope="col">Graduation Date</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <!-- Iteration for rendering students with line 42 -->
  <!-- Resource for table and button https://guides.rubyonrails.org/v7.1/layouts_and_rendering.html -->
  <tbody>
    <% @students.each_with_index do |student, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.major %></td>
        <td><%= student.graduation_date %></td>
        <td>
          <!-- Button to lead to the "Show Student" form -->
          <%= link_to 'Show', student_path(student), class: 'btn btn-primary' %>
        </td>
        <td>
          <!-- Button to lead to the "Edit Student" form. Design choice for button for Teal -->
          <%= link_to 'Edit', edit_student_path(student), class: 'btn btn-info' %>
        </td>
        <td>
          <!-- Button to lead to the Delete Student. Button will be red to show it is a dangerous button -->
          <%= link_to 'Delete', student_path(student), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

      </tr>
    <% end %>
  </tbody>
</table>




<%= render 'search_form', search_params: @search_params %>

<!-- For case of no empty search and for Rspec test #3 -->
<% if @students_message.present? %>
  <p><%= @students_message %></p>
<% end %>

<%= link_to "New student", new_student_path %>
<br>
<!-- Added a Show Students button to index -->
<!-- Instead, my workaround is to just show all majors since majors must be choosen through a selection list now :D -->
<%= link_to 'Show All Students', students_path(search: { major: ["Computer Engineering BS", 
"Computer Information Systems BS", "Computer Science BS", "Cybersecurity Major", 
"Data Science and Machine Learning Major"] }), class: 'btn btn-primary' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/students/studentlist.html.erb
<h1>Students</h1>
<!-- Testing for making custom routes in index -->
<!-- Custom route to show all Students -->
<!-- Currently not bein used -->
<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>